### PR TITLE
Add a --format and a --json option to the search command

### PR DESCRIPTION
**Pull request by talwrii**
The --json options makes it easier to use search results programmatically. It also acts as documentation for --format.

--format is quite useful for ad hoc querying (e.g - how many bugs does each project have, how many bugs are there of this priority etc etc)

### CODE REVIEW

**Comment by williamh** [comment]
This pull request has far too many unrelated features for me to review.
A pull request should contain commits related to one feature only and should be on a topic branch instead of master.

I'm very interested in this code, but I need it in small pull requests so that I can review and merge them more easily.

Thanks,

William

**Comment by talwrii** [comment]
Aha, yes. I issued a pull request from master a few months ago, forgot about the merge request, and kept on adding stuff. I shall split this into a few topic branches for you.

**Comment by talwrii** [comment]
That being said most of my pull requests are probably going to consist of one patch :)

**Comment by talwrii** [comment]
Pull requests:

--format and --json options for search
https://github.com/williamh/pybugz/pull/92

**Pull request closed without merging**
